# Generated by Django 4.1.3 on 2022-11-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('disponible', models.BooleanField()),
                ('fechaIncorporacion', models.DateField()),
                ('nombrePyme', models.CharField(max_length=30)),
            ],
        ),
    ]
